# Generated by Django 2.2.5 on 2019-10-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
