# Generated by Django 2.2.5 on 2019-10-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191017_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('primary', '優先'), ('success', '普通'), ('info', '後回し可')], default='danger', max_length=150),
            preserve_default=False,
        ),
    ]
